### ISSUE TITLE
Error with BuddyPress 11.1.0 and Two-Factor 0.8.1

### ISSUE THREAD

**Issue by astanabe** [r-a-y/bp-two-factor#1]
Hello,
I'm using this plugin with BuddyPress and Two-Factor.
Thank you very much for your work.

After updating BuddyPress and Two-Factor to the latest version, the BuddyPress Settings page is no longer displayed correctly.
The debug message is the following.
```
PHP Fatal error:  Uncaught Error: Call to undefined method Two_Factor_Totp::user_two_factor_options_update() in wp-content/plugins/bp-two-factor-master/hooks/settings.php:91
```

When I downgraded the Two-Factor plugin to 0.7.3, this error fixed.
Best regards,

**Comment by r-a-y** [comment]
Thanks for the report. It looks like the Two Factor plugin removed the previous `user_two_factor_options_update()` method in their new v8.0 release. I'm looking into it.

**Comment by r-a-y** [comment]
I've got some updates that fixes the immediate problem. Please pull the latest master branch or download the latest copy of the plugin from the repo.

There are still some usability problems I need to address, particularly when TOTP is successfully set up or not, but at least a fatal error will no longer be displayed now. Still looking if I can fix some of these things with JS.

**Comment by astanabe** [comment]
Thank you for your rapid work!
I downloaded, installed and tested latest version, and it correctly worked.
Thanks, again.

**Comment by r-a-y** [comment]
Glad it worked for you! I've added some more commits so the previous functionality of my plugin should be fully compatible with two-factor v0.8.0 now. Please give it a test when you have a chance.
